# -*- coding: utf-8 -*-
"""ORM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jb3VmsJzqkugkdXIdJId0eaNBUIQL-Gq
"""

!pip install peewee

from peewee import *

import psycopg2
#from psycopg2.extensions import ISOLATION_LEVEL_SERIALIZABLE

db = PostgresqlDatabase('postgres', user='postgres', password ='postgres')
                        #,host='db-host',isolation_level=ISOLATION_LEVEL_SERIALIZABLE)

# никак не хочет работать, пыталась прописывать пути к БД, 
# добавлять уровень изоляции, начитавшись про другие версии,
# но всё безуспешно
db.connect()
#conn = db.connection()
#conn.set_isolation_level(ISOLATION_LEVEL_SERIALIZABLE)

class GRADE_TEST(Model):
    grade_id = IntegerField()
    student_id = CharField()
    grade_dt = DateField()
    semester = IntegerField()
    lec_academ_sub_id = IntegerField()
    type_control = CharField()
    grade_numb = IntegerField()
class Meta:
        database = db

class PROGRESS_TEST (Model):
    progress_id = IntegerField()
    grade_id = ForeignKeyField(GRADE_TEST, related_name = 'grade_id')

class Meta:
        database = db

# не работает из-за проблемы соединения наверное
PROGRESS_TEST.create_table() 
GRADE_TEST.create_table()

from datetime import date
# попытка заполнить две строчки таблицы с оценками
grade_1 = GRADE_TEST(grade_id = '1', 
                    student_id = '123455/2019', 
                    grade_dt = '15.06.2019',
                    semester ='2',
                    lec_academ_sub_id ='4',
                    type_control = 'экзамен',
                    grade_numb = '5',
                    is_relative=True)
grade_1.save() 
grade_2 = GRADE_TEST(grade_id = '2', 
                    student_id = '123456/2019', 
                    grade_dt = '15.06.2019',
                    semester ='2',
                    lec_academ_sub_id ='4',
                    type_control = 'экзамен',
                    grade_numb = '3',
                    is_relative=True)  
grade_2.save()

